name: cppcheck

on:
  workflow_dispatch:
  push: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run cppcheck on code
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install cppcheck
      run: |
        apt-get install -y cppcheck
    - name: Run cppcheck
      run: |
        cppcheck *.cpp
